from enum import Enum

N_NODES = 10
SIMULATION_TICKS = 100000
PROBABILITY_OF_SENDING_PACKET = 0.6
SIFS = 2  # 2 ticks
DIFS = 2 * SIFS + 5
DATA_MIN_SIZE = 100
DATA_MAX_SIZE = 299
ACK_MAX_WAIT_TIME = DATA_MIN_SIZE

CW_MIN = 31



class ChannelStatType(Enum):

    TOTAL_GENERATED_PACKETS = 0
    SENT_PACKETS = 1
    COLLISIONS = 2
    AVG_PACKET_LOSS_PERCENTAGE = 3
    TOTAL_RETRANSMITTED_PACKET_AFTER_ACK_LOST = 5
    TOTAL_NODES = 4

class NodeStatType(Enum):
    SENT_PACKET = 0
    RECEIVED_PACKET = 1
    CW_ENTERS = 2
    CW_INCREASE = 3
    CW_TOTAL_WAITING_TICKS_TIME = 4
    GENERATED_PACKETS = 5
    PACKET_LOSS_PERCENTAGE = 6
    RETRANSMITTED_PACKET_AFTER_ACK_LOST = 7

DEFAULT_CHANNEL_STATS = {
    ChannelStatType.TOTAL_GENERATED_PACKETS: 0,
    ChannelStatType.SENT_PACKETS: 0,
    ChannelStatType.COLLISIONS: 0,
    ChannelStatType.AVG_PACKET_LOSS_PERCENTAGE: 0,
    ChannelStatType.TOTAL_RETRANSMITTED_PACKET_AFTER_ACK_LOST: 0,
    ChannelStatType.TOTAL_NODES: N_NODES
}

DEFAULT_NODE_STATS = {
    NodeStatType.PACKET_LOSS_PERCENTAGE: 0,
    NodeStatType.GENERATED_PACKETS: 0,
    NodeStatType.SENT_PACKET: 0,
    NodeStatType.RECEIVED_PACKET: 0,
    NodeStatType.CW_ENTERS: 0,
    NodeStatType.RETRANSMITTED_PACKET_AFTER_ACK_LOST: 0,
    NodeStatType.CW_INCREASE: 0,
    NodeStatType.CW_TOTAL_WAITING_TICKS_TIME: 0
}

class ChannelStatus(Enum):
    CLEAR = 0
    BUSY = 1


class NodeStatus(Enum):
    IDLE = 0
    WAITING_DIFS_FOR_SENDING = 3
    WAITING_ACK = 6
    PACKET_RECEIVED_READY_TO_SEND_ACK = 7
    RECEIVING_PACKET = 5
    SENDING_PACKET = 2
    WAIT_UNTIL_CHANNEL_IS_CLEAR = 4
    CONTENTION_WINDOW = 1
