from enum import Enum

N_NODES = 50
SIMULATION_TICKS = 100000
PROBABILITY_OF_SENDING_PACKET = 0.01
SIFS = 2  # 2 ticks
DIFS = 2 * SIFS + 5
DATA_MIN_SIZE = 100
DATA_MAX_SIZE = 299
ACK_MAX_WAIT_TIME = DATA_MIN_SIZE

CW_MIN = 31


class PacketStatus(Enum):
    GENERATED = 0
    SENT_RTS = 1
    SENT_DATA = 2




class ChannelStatType(Enum):

    TOTAL_GENERATED_PACKETS = 0
    SENT_PACKETS = 1
    COLLISIONS = 2
    AVG_PACKET_LOSS_PERCENTAGE = 3
    TOTAL_RETRANSMITTED_PACKET_AFTER_ACK_LOST = 5
    TOTAL_NODES = 4

class NodeStatType(Enum):
    SENT_PACKET = 0
    RECEIVED_PACKET = 1
    CW_ENTERS = 2
    CW_INCREASE = 3
    CW_TOTAL_WAITING_TICKS_TIME = 4
    GENERATED_PACKETS = 5
    PACKET_LOSS_PERCENTAGE = 6
    RETRANSMITTED_PACKET_AFTER_ACK_LOST = 7

DEFAULT_CHANNEL_STATS = {
    ChannelStatType.TOTAL_GENERATED_PACKETS: 0,
    ChannelStatType.SENT_PACKETS: 0,
    ChannelStatType.COLLISIONS: 0,
    ChannelStatType.AVG_PACKET_LOSS_PERCENTAGE: 0,
    ChannelStatType.TOTAL_RETRANSMITTED_PACKET_AFTER_ACK_LOST: 0,
    ChannelStatType.TOTAL_NODES: N_NODES
}

DEFAULT_NODE_STATS = {
    NodeStatType.PACKET_LOSS_PERCENTAGE: 0,
    NodeStatType.GENERATED_PACKETS: 0,
    NodeStatType.SENT_PACKET: 0,
    NodeStatType.RECEIVED_PACKET: 0,
    NodeStatType.CW_ENTERS: 0,
    NodeStatType.RETRANSMITTED_PACKET_AFTER_ACK_LOST: 0,
    NodeStatType.CW_INCREASE: 0,
    NodeStatType.CW_TOTAL_WAITING_TICKS_TIME: 0
}

class ChannelStatus(Enum):
    CLEAR = 0
    BUSY = 1


def waiting_packet_status():
    return [NodeStatus.WAITING_DATA, NodeStatus.WAITING_ACK, NodeStatus.WAITING_CTS,NodeStatus.IDLE, NodeStatus.WAITING_UNTIL_CHANNEL_IS_CLEAR, NodeStatus.CONTENTION_WINDOW]

class NodeStatus(Enum):

    # IDLE,WAITING_DIFS,WAITING_UNTIL_CHANNEL_IS_CLEAR,CONTENTION_WINDOW,SENDING_PACKET,WAITING_CTS,WAITING_ACK,WAITING_DATA,RECEIVING_PACKET


    IDLE = 0
    WAITING_DIFS = 2
    WAITING_UNTIL_CHANNEL_IS_CLEAR = 1
    CONTENTION_WINDOW = 3
    SENDING_PACKET = 4
    WAITING_CTS = 5
    WAITING_ACK = 6
    WAITING_DATA = 7




